let suggestions = [
    "Avatar 2",
    "Dune 2",
    "Represalii",
    "Top Gun 2",
    "Venom",
    "The Marvels",
    "The Flash",
    "Napoleon",
    "Wonka",
    "Barbie",
    "Poor Things",
    "Parasite",
    "Champions",
    "Puppy Love",
    "Strays",
    "Casa Gucci",
    "Love Again",
    "Let Love Grow",
    "Robots",
    "Maybe I Do",
    "Sweet On You",
    "Brooklyn",
    "After",
    "Katak",
    "Migration",
    "Wish",
    "Mummies",
    "Minions 2",
    "Lightyear",
    "Space Jam",
    "The Fall Guy",
    "Furiosa",
    "Deadpool 3",
    "Alien",
    "Beetlejuice 2",
    "Joker 2",
    "Gladiator 2",
];
